### ISSUE TITLE
Exception AssertionError: None when trying to ~upvote 

### ISSUE THREAD

**Issue by sdaugherty** [avrae/taine#6]
Was unable to upvote a feature request today because of the following error message.

> stephanie Today at 1:52 PM
> ~upvote AFR-117
> Taine, Hunter of Bugs BOT Today at 1:52 PM
> Error: Command raised an exception: AssertionError: None

**Comment by Dusk-Argentum** [comment]
This is likely caused by attempting to upvote a legacy report created before the upvote ticker in `~report` was added. Unfortunately due to the need for a legacy report, I can't exactly fix this one myself, and we'll have to wait for Zhu to fix it. Thanks for reporting the issue!

**Comment by mommothazaz123** [comment]
Looks like an error when Taine tries to post a comment with content as None (see add_attachment()). I won't have time to fix this today as I'll be flying internationally, @Dusk-Argentum you might be able to fix it.
